### PR TITLE
fix(chat): fix message border styles

### LINKED ISSUE #1737: Comic balloon style for messages
Outward bottom corner should look like this 
Screenshot 2020-03-19 at 19 04 30

### PR DESCRIPTION
**Pull request by clegirar**
Fixes #1737

### CODE REVIEW

File: js/packages/berty-storybook/chat/shared-components/Message.tsx [hunk 1]
```diff
@@ -111,10 +112,22 @@ export const Message: React.FC<MessageProps> = ({
...
+							</Text>
+							{payload.isMe && (
+								<Icon
+									name={payload.acknowledged ? 'navigation-2' : 'navigation-2-outline'}
+									width={12}
+									height={12}
+									fill={color.blue}
+								/>
+							)}
+							<Text style={[text.color.grey, padding.left.scale(3), _styles.dateMessage]}>
```
Comment (n0izn0iz) [inline js/packages/berty-storybook/chat/shared-components/Message.tsx]: I think we should remove the text if we add the icon

Comment (clegirar) [reply js/packages/berty-storybook/chat/shared-components/Message.tsx]: I think it's good if we have both for more clarity, if we have just an icon the user may have a different understanding from ours no ?

Comment (n0izn0iz) [reply js/packages/berty-storybook/chat/shared-components/Message.tsx]: my bad I had bad memory of the mockups
