### PR TITLE
fix(messenger): android footer animation

### LINKED ISSUE #3210: Conversation footer broken an Android
Send button on android does not appear when we type
screenshot

### PR DESCRIPTION
**Pull request by clegirar**
Fix #3210 

Signed-off-by: clegirar <clemntgirard@gmail.com>

### CODE REVIEW

File: js/packages/components/chat/common.tsx [hunk 1]
```diff
@@ -9,10 +9,8 @@ import {
 	ViewToken,
 	Animated,
 	Easing,
-	Keyboard,
 } from 'react-native'
 import { Icon, Text } from '@ui-kitten/components'
-import DeviceInfo from 'react-native-device-info'
```
Comment (n0izn0iz) [inline js/packages/components/chat/common.tsx:15]: please also remove the package from dependencies

**Comment by zxxma** [comment]
Some little bugs remaining : 
- the '+' button got a strange effect on
- and some bugs related to the BlurView, but not in this PR
- the keyboard is not perfectly aligned with the footer when it's open

All these bugs can be fix in other PRs, so for me it's a LGTM 👍
