### PR TITLE
fix(front): disable autocomplete/capitalization for sensitive fields

### LINKED ISSUE #1996: Handle "Delete " (autocomplete-inserted space) in delete account modal
iOS may insert a space after autocompleting a word, so "Delete " will be entered into the Delete Account modal. The space should be accepted. Or we should disable autocomplete in this field.

Brought up in testing session #2

### PR DESCRIPTION
**Pull request by ekelen**
Blocked by #2022 (since this isn't an urgent issue and it will be much faster to rebase, as 2022 changes yarn.lock)

Closes #1996

### CODE REVIEW

File: js/packages/components/modals/DeleteAccount.tsx [hunk 1]
```diff
@@ -138,6 +139,8 @@ const DeleteAccountContent: React.FC<{}> = () => {
 					]}
 					value={deleteConfirmation}
 					onChangeText={setDeleteConfirmation}
+					autoCorrect={false}
+					autoCapitalize='none'
```
Comment (n0izn0iz) [inline js/packages/components/modals/DeleteAccount.tsx:143]: if we disable `autoCapitalize` we should also set the `DELETE_STR` to 'delete' (without cap) IMO

Comment (ekelen) [reply js/packages/components/modals/DeleteAccount.tsx:143]: Hah, I agree 100%, I did it in my last push, then set it back. Doing.
