### PR TITLE
fix: UI front fixes

### LINKED ISSUE #4308: Account: User is able to save blank name
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

2.391.3

### OS

iOS

### OS version

iOS 15.5 / Android 12

### Device

iPhone 13 Max Pro / Samsung s21+ 

### Steps to reproduce

1. Login to the Berty app and navigate to the Inbox page
2. Click user Icon at top right corner to navigate on Settings page
3. Click on the user icon at top of settings page
4. Delete user name and add only one spacing 

### Current behavior

Save button is available and user is able to save blank name.

https://user-images.githubusercontent.com/105677764/180239236-c97cfbff-71ca-4464-ad34-8f8c1e81aa8a.mp4

### Expected behavior

If user did not provide any letters/numbers/symbols, he shouldn't be able to save his name. Save changes button shouldn't not appear for spacing.

### Other

_No response_

### PR DESCRIPTION
**Pull request by clegirar**
Fixes #4308 #4310 #4223 

Signed-off-by: clegirar <clemntgirard@gmail.com>

### CODE REVIEW

File: js/packages/components/chat/message/user-message/user-message-box/FileMessage.tsx [hunk 1]
```diff
@@ -65,7 +65,7 @@ export const FileMessage: React.FC<{
 					},
 				]}
 			>
-				{medias[0].filename}
+				{medias[0].filename?.substring(0, 20).concat('...')}
```
Comment (n0izn0iz) [inline js/packages/components/chat/message/user-message/user-message-box/FileMessage.tsx:68]: why not use the "ellipsize" feature of react-native text ?

**Review by n0izn0iz — APPROVED** [review]
LGTM except comment

File: js/packages/components/chat/message/user-message/user-message-box/FileMessage.tsx (hunk 1 above)
Comment (clegirar) [reply js/packages/components/chat/message/user-message/user-message-box/FileMessage.tsx:68]: Yep i can use it 👍
